version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - http.host=0.0.0.0
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml:ro
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kibana
    hostname: kibana
    volumes:
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    restart: always
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local